name: Create Release

on:
  push:
    branches:
      - main

    paths-ignore:
      - "**/*.md"
      - "**/.vscode/**"

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure version
        shell: bash
        run: |
          dateVer="$(date +'%Y.%m.%d')"
          dateVer="$dateVer.${{ github.run_number }}"
          echo "Version = $dateVer"
          echo "version=$dateVer" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.STRIVEBOT_TOKEN }}
          prerelease: false
          tag_name: ${{ env.version }}
          generate_release_notes: true
          body: "${{ env.body }}"

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: strivebot
          password: ${{ secrets.STRIVEBOT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VERSION=${{ env.version }}
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.version }}
